apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "magicode.fullname" . }}
  labels:
    {{- include "magicode.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "magicode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "magicode.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "magicode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MAIL_HOST
              value: smtp.gmail.com
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: magicode-mail-creds
                  key: password
            - name: MAIL_PORT
              value: '587'
            - name: MAIL_TO
              value: magicode@outlook.com
            - name: MAIL_USERNAME
              value: magicodeuk@gmail.com
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
