apiVersion: v1
data:
  host: {{ .Values.mail.host | b64enc | quote }}
  password: {{ .Values.mail.password | b64enc | quote }}
  port: {{ .Values.mail.port | b64enc | quote }}
  to: {{ .Values.mail.to | b64enc | quote }}
  username: {{ .Values.mail.username | b64enc | quote }}
kind: Secret
metadata:
  name: magicode-mail-creds
type: Opaque
